export * from './enterText.js'
export * from './helpText.js'
export * from './stickersMap.js'
export * from './weatherEmoji.js'
export * from './weatherNotificationAddedText.js'
export * from './weatherNotificationNoTime.js'
export * from './weekDaysTranslationMap.js'
